// src/config/initialRows.js
// Datos de ejemplo iniciales para la tabla de viviendas

export const initialRows = [
  {
    id: 1,
    link: "https://www.example.com/property/1",
    emoji: "",
    kpi: 0,
    precio: 250000,
    superficie: 120,
    eurom2: 2083,
    habitaciones: 3,
    baños: 2,
    planta: "Intermedia",
    ascensor: "Sí",
    calefaccion: "Sí",
    fachada: "Exterior",
    garaje: "No",
    terraza: "Sí",
  },
  {
    id: 2,
    link: "https://www.example.com/property/2",
    emoji: "",
    kpi: 0,
    precio: 210000,
    superficie: 90,
    eurom2: 2333,
    habitaciones: 2,
    baños: 1,
    planta: "Baja",
    ascensor: "No",
    calefaccion: "No",
    fachada: "Interior",
    garaje: "Sí",
    terraza: "No",
  },
  {
    id: 3,
    link: "https://www.example.com/property/3",
    emoji: "",
    kpi: 0,
    precio: 320000,
    superficie: 150,
    eurom2: 2133,
    habitaciones: 3,
    baños: 2,
    planta: "Ático",
    ascensor: "Sí",
    calefaccion: "Sí",
    fachada: "Exterior",
    garaje: "Sí",
    terraza: "Sí",
  },
];
