name: Validate PR branch name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(release|feature|fix|chore).+$ ]]; then
            echo "ERROR: La rama debe empezar por release, feature, fix o chore"
            exit 1
          fi