name: Bump VERSION on merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        id: branch
        run: echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Read current version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          VERSION="${{ steps.version.outputs.current_version }}"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          BRANCH="${{ steps.branch.outputs.branch_name }}"
          if [[ "$BRANCH" =~ ^release ]]; then
            MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
          elif [[ "$BRANCH" =~ ^feature ]]; then
            MINOR=$((MINOR+1)); PATCH=0
          elif [[ "$BRANCH" =~ ^fix ]]; then
            PATCH=$((PATCH+1))
          elif [[ "$BRANCH" =~ ^chore ]]; then
            echo "No version bump for chore branches"; exit 0
          else
            echo "ERROR: Rama no válida para versionado"; exit 1
          fi
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $MAJOR.$MINOR.$PATCH > VERSION
          echo "new_version=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT

      - name: Commit and push VERSION
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add VERSION
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}"
          git push